on:
  push:
    paths:
    - 'projects/ngx-filemanager-core/**'

name: Core Build and Publish
jobs:
  deploy-core:
    name: Deploy Core
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.1
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Build Core
        run: |
          npm run-script core-build
      - name: Publish Core
        if: github.ref == 'refs/heads/master'
        uses: benwinding/merge-release@master
        env:
          DEPLOY_DIR: dist/ngx-filemanager-core
          SRC_PACKAGE_DIR: projects/ngx-filemanager-core
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GIT_TAG_SUFFIX: -core
